services:
  fastapi:
    restart: unless-stopped
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        published: 8000
    env_file:
      - .env
    deploy:
     resources:
       reservations:
         memory: 1024M

